### PR TITLE
Fixes pAI camera bugs

### PR DESCRIPTION
**Pull request by Teaganyas**
The following applies to pAI Cameras
-No longer lag behind
-No longer get stuck in lockers
-No longer prevent carrier from dragging mobs

### CODE REVIEW

**Comment by FlavoredCactus** [comment]
whats with all the commented out procs?
the follow_pai proc seems drastically changed.
there is a while loop within another while loop.

all this looks just unsafe to me.

**Comment by Teaganyas** [comment]
The commented out procs are unused, were originally used for a WIP feature to allow pAI to use AI camera network

The while loop within the while loop prevents lockers from entirely ending the loop. 

The loop itself actually comes from an approved change which fixed observer ghosts following players.

**Comment by FlavoredCactus** [comment]
You practically copy pasted the observer code and didn't even check over what was pasted.

i wouldn't comment out code as well
copy pasted from discord
```its pratically copy paste
you even kept alpha = 0
and mouse_opacity = 0
your casting a target variable
when card is already defined
card
instead of 
var/target = paicard
while(client)
user logs out
loop ends
and never picks back up```

**Comment by FlavoredCactus** [comment]
Closed on request

**Pull request closed without merging**
