### PR TITLE
Adds "Mentorhelp" tab

### PR DESCRIPTION
**Pull request by DingleFlop**
Adds a "Mentorhelp" tab next to the "Adminhelp" tab for ease of
mentoring workflow.

### CODE REVIEW

**Comment by FlavoredCactus** [comment]
Is this tab visible to non-mentors when they boot up their game?

**Comment by DingleFlop** [comment]
Yes, it's visible to everyone, always, just like the adminhelp tab

**Comment by DingleFlop** [comment]
Check the thread for pics: http://llagaming.net/forums/threads/mentor-tab.5352/

**Comment by DingleFlop** [comment]
Me, Drache and Batts tested this today, and it is completely fine and works without leaking information to the player or to Mentors.

**Pull request closed without merging**
